version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    commit-message:
      include: scope
      prefix: chore
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - peppapig450

  - package-ecosystem: "uv"
    directory: /scripts
    schedule:
      interval: "daily"
    commit-message:
      include: scope
      prefix: chore
    labels:
      - "dependencies"
      - "python"
    assignees:
      - peppapig450
